services:
  - type: web
    name: accounting-system
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: SECRET_KEY
        sync: false
